---
title: "Teaching"
title-block-banner: false
page-layout: article
---

## Teaching courses

I teach in a practical way, encouraging participation, critical thinking, and open discussion. Classes are flexible and respectful, supporting throughout their learning process. Materials are regularly updated, here I include the latest version for each course.

### Undergraduate teaching

- **Análisis y Evaluación de los Sistemas de Documentación para las Empresas**. 2026-present
- **Nuevas Tendencias en los Servicios de Información**. 2026-present
- **Documentación Aplicada a la Traducción**. 2020-present | [Content](https://sites.google.com/go.ugr.es/nrobinsongarcia-docencia/documentaci%C3%B3n-aplicada-a-la-traducci%C3%B3n)

### Master's teaching 

- **Nuevas métricas de la ciencia en red**. 2019-present | [Content](https://docs.google.com/document/d/1WHZDao5eQwVRT-jI8Fr8aZBXWMp0TohGVnkHXDtaD_A/edit?usp=sharing)

### Doctoral teaching

- **Herramientas Computacionales para el Análisis y Visualización de Datos en CC Sociales**. 2024-present
- **Cómo escribir y publicar artículos científicos en CC Sociales y Humanidades**. 2022-present | [Content](https://elrobin.github.io/escritura-academica/)

### Past courses

- **Técnicas esenciales para preparar una revisión de la literatura**
  - July 5, 2026. 2h. GECOS, Universidad de Salamanca [Material](https://doi.org/10.5281/zenodo.21257404)
  - April 10, 2026. 4h. Campus de Ceuta, Universidad de Granada [Material](https://doi.org/10.5281/zenodo.21257136)
- **CV and social media profiles** June 26, 2023. 3h. INGENIO (CSIC-UPV)
- **Diseño y aplicación de análisis de bibliométricos**. January 16-19, 2023. 12h. Universidad de Costa Rica. [Materials](https://doi.org/10.5281/zenodo.7556999)
- **Elaboración del CV en entornos digitales** 2021-2023. 10h. Social Sciences Doctoral Programme, University of Granada.

## Supervision

I supervise and mentor students at different stages of their academic careers, including PhD candidates, Master’s students, and early-career researchers.

- [**Elvira González-Salmón**](https://sites.google.com/go.ugr.es/egonzalezsalmon/). Niños furbito y niñas lo que sea: The gender gap in science and the consequences for the scientific knowledge that is created. University of Granada. Ongoing
- [**Victoria Di Césare**](https://sites.google.com/view/vdicesare). El costo de realizar
investigación local: implicaciones para las trayectorias científicas y la
producción de conocimiento. University of Granada. Ongoing
- [**Néstor Mir Planells**](https://nestormirplanells.wordpress.com/). Universitat Politècnica de Valéncia. Ongoing
- [**Alwaleed Alkhaja**](https://creativecommons.org/person/alwaleed-alkhaja/) University of Tampere On-going