var SDPA={init:function(){SDPA.sendIndex();$(window).load(SDPA.sendPage());$(window).load(SDPA.sendResources(2E3));$(window).unload(function(){SDPA.sendResources(0)})},hashCode:function(b){var a=0;if(0==b.length)return a;for(i=0;i<b.length;i++)var d=b.charCodeAt(i),a=(a<<5)-a+d,a=a&a;return a},sendIndex:function(){var b=SDM.sds,a=SDM.tid,d=SDPA.hashCode(b),f=SDPA.hashCode(a),c;c="cpc=SD&pagetype="+SDM.pageType;c+="&sds="+b;c+="&tid="+a;c+="&sdsh="+d;c+="&tidh="+f;c=void 0!=window.performance?c+("&ns="+
window.performance.timing.navigationStart):c+("&ns="+Date.now());b=SDM.pru+"/idx?"+c;$("#sdpa").append('<img style="display:none" src="'+b+'">')},sendPage:function(){var b=window.performance,a;a="cpc=SD&key="+encodeURIComponent(SDM.pageTransKey);a+="&pagetype="+SDM.pageType;a+="&sdsh="+SDPA.hashCode(SDM.sds);a+="&tidh="+SDPA.hashCode(SDM.tid);void 0!==SDM.tm.ahm&&(a+="&ahm="+SDM.tm.ahm);void 0!==SDM.tm.chm&&(a+="&chm="+SDM.tm.chm);document.location.href&&(a+="&href="+encodeURIComponent(document.location.href));
document.documentElement.clientWidth&&document.documentElement.clientHeight&&(a+="&winHeight="+document.documentElement.clientHeight,a+="&winWidth="+document.documentElement.clientWidth);a+="&domCount="+document.getElementsByTagName("*").length;if(void 0!=window.optimizely){for(var d=window.optimizely.data.state.activeExperiments,f=d.length,c="&oexp=",e=0;e<f;e++)c=e+1<f?c+(d[e]+"|"):c+d[e];a+=c}a+="&ud="+SDM.ud;a=void 0!=SDM.isOAarticle?"true"==SDM.isOAarticle?a+"&oa=1":a+"&oa=0":a+"&oa=-1";if(void 0!=
window.performance){if(b.timing)if(b=b.timing,0<b.loadEventEnd){for(var g in b)a+="&"+g+"="+b[g];"undefined"!=typeof chrome&&chrome.loadTimes()&&(a+="&msFirstPaint="+SDPA.toInt(1E3*chrome.loadTimes().firstPaintTime));a=SDM.pru+"/pageReport?"+a;$("#sdpa").append('<img style="display:none" src="'+a+'">')}else setTimeout(SDPA.sendPage,100)}else a=SDM.pru+"/pageReport?"+a,$("#sdpa").append('<img style="display:none" src="'+a+'">')},toInt:function(b){return Math.round(Number(b)).toString()},buildResources:function(b,
a){var d=window.performance.timing,f=$("iframe"),c=d.navigationStart,e=d.responseStart-c,g=d.domInteractive-c,l=d.loadEventEnd-c,d=window.performance.getEntries(),k=[],m=SDPA.hashCode(SDM.sds),n=SDPA.hashCode(SDM.tid);k.push({ent:a,sdsh:m,tidh:n,ns:c,ttfb:e,pgi:g,pgl:l});for(c=SDPA.sc[SDPA.sc.length-1];c<b;c++)if(e=d[c].name.match(/^https?\:\/\/([^\/\s]+)((\/\w+)*\/)([\w\-\.]+[^#?\s]+)(.*)?(#[\w\-]+)?$/i),null==e?e=g="":(g=e[2].split("/"),g=4<=g.length?g[1]+"/"+g[2]+"/"+g[3]:3==g.length?g[1]+"/"+
g[2]:2==g.length?g[1]:"",e=e[1]),k.push({i:c,tm:SDPA.toInt(d[c].startTime)+"|"+SDPA.toInt(d[c].responseStart)+"|"+SDPA.toInt(d[c].duration),t:d[c].initiatorType,h:e,p:g}),"iframe"===d[c].initiatorType&&void 0!=f[SDPA.u]){if(-1!=f[SDPA.u].src.match(/^https?\:\/\/([^\/?#]+)(?:[\/?#]|$)/i)[1].indexOf("www.sciencedirect.com"))for(ifo=f[SDPA.u].contentWindow.window.performance.getEntries(),ic=0;ic<ifo.length;ic++){e=ifo[ic].name.match(/^https?\:\/\/([^\/\s]+)((\/\w+)*\/)([\w\-\.]+[^#?\s]+)(.*)?(#[\w\-]+)?$/i);
if(null==e)var h="";else 2<e.length&&(h=e[2].split("/"),h=4<=h.length?h[1]+"/"+h[2]+"/"+h[3]:3==h.length?h[1]+"/"+h[2]:2==h.length?h[1]:"");k.push({i:c,ifr:ic,tm:SDPA.toInt(ifo[ic].startTime)+"|"+SDPA.toInt(ifo[ic].responseStart)+"|"+SDPA.toInt(ifo[ic].duration),t:ifo[ic].initiatorType,h:e[1],p:h})}SDPA.u++}f=encodeURI(JSON.stringify(k));f=SDM.pru+"/resource?"+f;$("#sdpa").append('<img style="display:none" src="'+f+'">');SDPA.sc.push(b);SDPA.loopc=[0]},ec:[0],sc:[0],loopc:[0],u:0,sendResources:function(b){var a=
"undefined"!=typeof b&&0<b?b:0;if(void 0!=window.performance&&(b=window.performance,"undefined"!=typeof b.getEntries))if(b=b.getEntries().length,SDPA.ec.push(b),ecl=SDPA.ec.length-1,ecC=SDPA.ec[ecl]-SDPA.ec[ecl-1],ecLast=SDPA.ec[ecl-1],SDPA.ec[ecl]==SDPA.ec[ecl-1]||15>SDPA.ec[ecl]-SDPA.ec[ecl-1])SDPA.loopc.push(0),8>SDPA.loopc.length&&setTimeout(function(){SDPA.sendResources(a)},a);else{if(15<ecC)for(var d=SDPA.sc[SDPA.sc.length-1],f=d;0<b-f;f+=15)d=SDPA.sc[SDPA.sc.length-1],SDPA.buildResources(f,
b),15>b-f&&SDPA.buildResources(b,b);setTimeout(function(){SDPA.sendResources(a)},a)}}};
