(function(e){Drupal.behaviors.HighWire_AltMetrics={attach:function(t,r){if(typeof Modernizr!='undefined'&&!Modernizr.mutationobserver){if(typeof(Drupal.settings.MutationObserver)!='undefined'&&Drupal.settings.MutationObserver!==null){var n=Drupal.settings.MutationObserver.js;e.when(e.getScript(n)).done(function(){i()})}}
else{i()};function i(){var t=e('.altmetric-embed'),r=e('.pane-highwire-altmetrics'),n=new MutationObserver(function(e,n){var i=this;if(t[0]){e.forEach(function(e){if(e.type=='attributes'){if(t.hasClass('altmetric-hidden')){r.hide().next('.panel-separator').hide();i.disconnect()}}})}}),i={attributes:!0,subtree:!0};n.observe(t[0],i)}}}})(jQuery);(function(n){Drupal.behaviors.bmjJumpLinks={attach:function(t,u){n(document.body,t).once('bmjJumpLinks',function(){var t=u.bmjJumpLinks.jumplinks,e=u.bmjJumpLinks.sections,m=t.length;for(i=0;i<m;i++){if(n(e[i]).length){n('.pane-bmjj-jumplinks .pane-content .highwire-list ul').append('<li>'+t[i]+'</li>')}}})}}})(jQuery);(function(o){Drupal.behaviors.bmjArticleDropdown={attach:function(t,a){o(document).one('ready',function(){o('.panels-ajax-tab').clone().appendTo(o('.mobile-art-drop-down'))});o('a.mobile-article-tab').on('click',function(t){t.preventDefault();t.stopImmediatePropagation();o('.mobile-art-drop-down').toggle();o(this).children('.icon-toggle').toggleClass('icon-plus').toggleClass('icon-close')});o('a.panels-ajax-tab-tab').on('click',function(){o('#mobile-tab-title p').html(o(this).html())})}}})(jQuery);(function(e){Drupal.behaviors.highwire_responsive_toggle={attach:function(i,s){var n=e('.highwire-responsive-toggle-group',i);n.each(function(){var i=e(this);i.prepend('<ul class="highwire-responsive-toggle-triggers"></ul>');var n=e('.highwire-responsive-toggle-triggers',i),s=i.children('.panel-pane');s.each(function(i){var a=e(this),l=a.find('.pane-title').html();n.append('<li class="trigger-'+i+'">'+l+'</li>');n.find('li.trigger-'+i).click(function(i){i.preventDefault();var l=a.hasClass('expanded'),d=e(this).hasClass('expanded');s.each(function(){e(this).removeClass('expanded')});n.find('li').removeClass('expanded');if(!l){a.addClass('expanded');e(this).addClass('expanded');a.find('#edit-keywords').focus()}
else{a.removeClass('expanded');e(this).removeClass('expanded')}});a.find('ul.menu li.expanded').each(function(){var i=e(this).find('ul.menu li').length;if(i==0||i==null){e(this).removeClass('expanded')}});a.find('ul.menu > li.expanded > a').click(function(i){i.preventDefault();var n=e(this);n.parent('li').toggleClass('show')})});e(document).click(function(n){if(!e(n.target).closest(i).length){if(i.children('.panel-pane').hasClass('expanded')){i.find('.highwire-responsive-toggle-triggers > li').removeClass('expanded');i.children('.panel-pane').removeClass('expanded')}}})})}}})(jQuery);(function(a){Drupal.behaviors.menu_attach_block={attach:function(t,n){a('a.menu-attach-block-drop-link.expand-on-hover',t).hover(function(){if(!(a(this).hasClass('dropped'))){e(a(this))}},function(){e(a(this))});a('a.menu-attach-block-drop-link.expand-on-click',t).click(function(t){e(a(this));t.preventDefault()});function e(t){if(t.hasClass('menu-ajax-enabled')){if(!t.hasClass('menu-ajax-loaded')){ajax_path=Drupal.settings.basePath+'menu_attach_block/ajax/'+(t).attr('data-block-id');a.ajax({type:'GET',url:ajax_path,data:'',dataType:'HTML',success:function(e){a(t).next('.menu-attach-block-wrapper').html(e);Drupal.attachBehaviors(t)}})}};a(t).next('.menu-attach-block-wrapper').slideToggle('fast');a(t).toggleClass('dropped')}}}}(jQuery));(function(e){Drupal.behaviors.panels_ajax_pane={attach:function(a){e('.panels-ajax-pane',a).once('panels-ajax-pane-once',function(){(function(a){e.ajax({type:'POST',data:Drupal.settings.panels_ajax_pane[a.data('pid')],url:Drupal.settings.basePath+'panels_ajax_pane/render',cache:!0,error:function(e,n,a){if(typeof console=='object'){console.error('Panels Ajax Pane Error: '+a)}}}).done(function(n){$title_span=e('span.panels-ajax-pane-title[data-pid='+a.data('pid')+']');if(n['markup']===!1){a.closest('.pane-panels-ajax-pane-content').remove();a.remove();$title_span.closest('.pane-title').remove();$title_span.parent().remove()}
else{a.append(n['markup']);$title_span.append(n['title']);a.find('style').append('head')};if(n['title']===!1){$title_span.closest('.pane-title').remove();$title_span.parent().remove()};Drupal.attachBehaviors(a)})})(e(this))})}}})(jQuery);(function(e){Drupal.behaviors.bmjjThemeScripts={attach:function(e,t){}};Drupal.behaviors.menu_attach_block={attach:function(t,n){e('a.menu-attach-block-drop-link.expand-on-hover',t).hover(function(){if(!(e(this).hasClass('dropped'))){i(e(this))}},function(){i(e(this))});e('a.menu-attach-block-drop-link.expand-on-click',t).click(function(t){i(e(this));t.preventDefault()});function i(t){if(t.hasClass('menu-ajax-enabled')){if(!t.hasClass('menu-ajax-loaded')){ajax_path=Drupal.settings.basePath+'menu_attach_block/ajax/'+(t).attr('data-block-id');e.ajax({type:'GET',url:ajax_path,data:'',dataType:'HTML',success:function(i){e(t).next('.menu-attach-block-wrapper').html(i);Drupal.attachBehaviors(t)}})}};e(t).next('.menu-attach-block-wrapper').toggle();e(t).toggleClass('dropped')}}};e(document).ready(function(e){e('#mini-panel-mobile_slide_out_menu .trigger-1').on('click',function(t){t.preventDefault();e('body').toggleClass('menu-out')});e('#mini-panel-mobile_slide_out_menu .trigger-0').on('click',function(t){t.preventDefault();e('body').removeClass('menu-out')});e('.menu-close').on('click',function(t){t.preventDefault();e(document).trigger('click')});e(document,'.menu-close').click(function(t){if(!e(t.target).closest(e('.highwire-responsive-toggle-group')).length){e('body').removeClass('menu-out')};if(!e(t.target).closest(e('.region-platmenu')).length){e('.region-platmenu .drop-menu').removeClass('dropped').nextAll('.menu-attach-block-wrapper').hide();e('.region-platmenu .drop-menu').children('[class*=icon]').removeClass('icon-arrow-up').addClass('icon-arrow-down')}});e('a.drop-menu').on('click',function(t){t.preventDefault();var i=e(t.target).closest(e('.region-platmenu')).find('.drop-menu'),n=!1;if(e(this).hasClass('dropped')){n=!0};i.removeClass('dropped');i.children('[class*=icon]').removeClass('icon-arrow-up').addClass('icon-arrow-down');i.nextAll('.menu-attach-block-wrapper').hide();if(n){e(this).removeClass('dropped');e(this).children('[class*=icon]').removeClass('icon-arrow-up').addClass('icon-arrow-down');e(this).nextAll('.menu-attach-block-wrapper').hide()}
else{e(this).toggleClass('dropped');e(this).children('[class*=icon]').toggleClass('icon-arrow-up').toggleClass('icon-arrow-down');e(this).next('a.menu-attach-block-drop-link').trigger('click')}});e('a.mobile-drop-down').on('click',function(t){t.preventDefault();e(this).toggleClass('dropped');e(this).children('[class*=icon]').toggleClass('icon-plus').toggleClass('icon-close');e(this).next('a.menu-attach-block-drop-link').trigger('click')});e.ajax({url:Drupal.settings.basePath+'sites/default/themes/bmjj/img/defs.svg'}).done(function(e){var t=document.createElement('div');t.style.display='none';t.innerHTML=new XMLSerializer().serializeToString(e.documentElement);document.body.insertBefore(t,document.body.childNodes[0])});e('.cookie-message-section').cookieBar({closeButton:'.wrap-icon svg'});e('.more-info').click(function(t){t.preventDefault();if(e('.more-info-text').hasClass('visible')){e('.more-info-text').removeClass('visible');e('#cookie-notice .more-info').find('svg').attr('class','icon-white icon-arrow-down');e('#cookie-notice .more-info').find('use').attr('xlink:href','/sites/default/themes/bmjj/img/defs.svg#icon-arrow-down')}
else{e('.more-info-text').addClass('visible');e('#cookie-notice .more-info').find('svg').attr('class','icon-white icon-arrow-up');e('#cookie-notice .more-info').find('use').attr('xlink:href','/sites/default/themes/bmjj/img/defs.svg#icon-arrow-up')}});e('.contributor-list .xref-aff, .author-affiliates .contributor-list .name').click(function(t){t.preventDefault();e('.author-affiliates .pane-title').trigger('click')});e('#sign-in').live('click',function(){if(e(this).attr('aria-expanded')=='false'){e(this).find('svg').attr('class','icon icon-white icon-arrow-up');e(this).find('use').attr('xlink:href','#icon-arrow-up');e(this).attr('aria-expanded','true')}
else{e(this).find('svg').attr('class','icon icon-white icon-arrow-down');e(this).find('use').attr('xlink:href','#icon-arrow-down');e(this).attr('aria-expanded','false')};e('.pane-challenge-opportunity-pane-dropdown').toggle()});e('.society-logins .ui-dialog-titlebar-close').live('click',function(){e(this).parents('.article-login').find('#sign-in').trigger('click');e(this).closest('.menu-attach-block-wrapper').siblings('.drop-menu').trigger('click')});if(e('#back-top').height()>=550){e('#article-top .article-pane').css('min-height',e('#back-top').height())};var t=Drupal.highwireResponsive.getCurrentLayout();if(t=='mobile'){e('.region-footersocial').appendTo('.menu-name-menu-footer-menu-1 > ul > li.first > ul')};e('.footer-links .content .menu > li[class*=\'col\'] > a').live('click',function(e){e.preventDefault()})});if(!Modernizr.svg){document.attachEvent('onreadystatechange',function(){if(document.readyState==='complete'){var t=jQuery('#logo-img').attr('src'),e=t.replace('.svg','.png');jQuery('#logo-img').attr('src',e);var t=jQuery('.logo-bmj-journals img').attr('src'),e=t.replace('.svg','.png');jQuery('.logo-bmj-journals img').attr('src',e)}})};Drupal.behaviors.bmjjHighwireMarkupProcess={attach:function(t,i){e('.panel-pane.pane-highwire-markup , .pane-highwire-contributors',t).each(function(){$pane=e(this);var i=e.trim(e('.highwire-markup >div',$pane).text()),t=e.trim(e('.highwire-markup >a',$pane).text());if(i==''&&t==''){$pane.hide()}})}};Drupal.behaviors.bmjjIE={attach:function(t,i){if(!Modernizr.svg){e('.fragment-image.lazyload').each(function(){e(this).attr('src',e(this).data('src')).removeClass('lazyload')});e('#sign-in,#menu-login').click(function(e){window.location='/user/login';e.preventDefault()});e('img[src*="svg"]').attr('src',function(){return e(this).attr('src').replace('.svg','.png')})}}}})(jQuery);!function(e,t){'function'==typeof define&&define.amd?define([],function(){return e.svg4everybody=t()}):'object'==typeof exports?module.exports=t():e.svg4everybody=t()}(this,function(){
/*! svg4everybody v2.0.0 | github.com/jonathantneal/svg4everybody */
;function e(e,t){if(t){var i=!e.getAttribute('viewBox')&&t.getAttribute('viewBox'),o=document.createDocumentFragment(),n=t.cloneNode(!0);for(i&&e.setAttribute('viewBox',i);n.childNodes.length;){o.appendChild(n.firstChild)};e.appendChild(o)}};function n(t){t.onreadystatechange=function(){if(4===t.readyState){var n=document.createElement('x');n.innerHTML=t.responseText,t.s.splice(0).map(function(t){e(t[0],n.querySelector('#'+t[1].replace(/(\W)/g,'\\$1')))})}},t.onreadystatechange()};function t(t){function o(){for(var f;f=d[0];){var t=f.parentNode;if(t&&/svg/i.test(t.nodeName)){var v=f.getAttribute('xlink:href');if(a&&(!r||r(v,t,f))){var p=v.split('#'),c=p[0],l=p[1];if(t.removeChild(f),c.length){var u=i[c]=i[c]||new XMLHttpRequest();u.s||(u.s=[],u.open('GET',c),u.send()),u.s.push([t,l]),n(u)}
else{e(t,document.getElementById(l))}}}};s(o,17)};t=t||{};var d=document.getElementsByTagName('use'),a='polyfill' in t?t.polyfill:/\bEdge\/12\b|\bTrident\/[567]\b|\bVersion\/7.0 Safari\b/.test(navigator.userAgent)||(navigator.userAgent.match(/AppleWebKit\/(\d+)/)||[])[1]<537,r=t.validate,s=window.requestAnimationFrame||setTimeout,i={};a&&o()};return t});/*!
 * jQuery Cookiebar Plugin
 * https://github.com/carlwoodhouse/jquery.cookieBar
 *
 * Copyright 2012, Carl Woodhouse
 * Disclaimer: if you still get fined for not complying with the eu cookielaw, it's not our fault.
 */
(function(e){e.fn.cookieBar=function(o){var n=e.extend({'closeButton':'none','secure':!1,'path':'/','domain':''},o);return this.each(function(){var i=e(this);i.hide();if(n.closeButton=='none'){i.append('<a class="cookiebar-close">Continue</a>');n=e.extend({'closeButton':'.cookiebar-close'},o)};if(e.cookie('cookiebar')!='hide'){i.show()};i.find(n.closeButton).click(function(){i.hide();e.cookie('cookiebar','hide',{path:n.path,secure:n.secure,domain:n.domain,expires:30});return!1})})};e.cookieBar=function(o){e('body').prepend('<div class="ui-widget"><div style="display: none;" class="cookie-message ui-widget-header blue"><p>By using this website you allow us to place cookies on your computer. They are harmless and never personally identify you.</p></div></div>');e('.cookie-message').cookieBar(o)}})(jQuery);
/*!
 * Dependancy:
 * jQuery Cookie Plugin
 * https://github.com/carhartl/jquery-cookie
 *
 * Copyright 2011, Klaus Hartl
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.opensource.org/licenses/GPL-2.0
 */
(function(e){e.cookie=function(i,n,o){if(arguments.length>1&&(!/Object/.test(Object.prototype.toString.call(n))||n===null||n===undefined)){o=e.extend({},o);if(n===null||n===undefined){o.expires=-1};if(typeof o.expires==='number'){var u=o.expires,c=o.expires=new Date();c.setDate(c.getDate()+u)};n=String(n);return(document.cookie=[encodeURIComponent(i),'=',o.raw?n:encodeURIComponent(n),o.expires?'; expires='+o.expires.toUTCString():'',o.path?'; path='+o.path:'',o.domain?'; domain='+o.domain:'',o.secure?'; secure':''].join(''))};o=n||{};var s=o.raw?function(e){return e}:decodeURIComponent,a=document.cookie.split('; ');for(var r=0,t;t=a[r]&&a[r].split('=');r++){if(s(t[0])===i)return s(t[1]||'')};return null}})(jQuery);;Drupal.highwireResponsive=Drupal.highwireResponsive||{};(function(e){var i='mobile',n=i,r=i,u=[],s=0,o=!1,p=function(e){r=n||i;n=e;t()},a=function(e){r=e;var o=u.indexOf(e);n=u[o-1]||i;t()};Drupal.highwireResponsive.getCurrentLayout=function(e){if(typeof e=='undefined'){e=!1};if(o){if(!e&&Drupal.highwireResponsive.isCurrentLayoutMobile(n)){return i}
else{return n}}
else if(typeof Drupal.omega!='undefined'){return Drupal.omega.getCurrentLayout()}};Drupal.highwireResponsive.getPreviousLayout=function(e){if(typeof e=='undefined'){e=!1};if(o){if(!e&&Drupal.highwireResponsive.isCurrentLayoutMobile(r)){return i}
else{return r}}
else if(typeof Drupal.omega!='undefined'){return Drupal.omega.getPreviousLayout()}};Drupal.highwireResponsive.isCurrentLayoutMobile=function(e){e=e||i;var n=Drupal.highwireResponsive.getMobileLayouts();if(n.indexOf(e)!=-1){return!0}
else{return!1}};Drupal.highwireResponsive.getMobileLayouts=function(){return['mobile','zero','xsmall']};var t=function(){e('body').removeClass('hw-responsive-layout-'+r).addClass('hw-responsive-layout-'+n);e.event.trigger('highwireResponsiveLayoutTransition',{from:r,to:n})};Drupal.behaviors.highwireResponsiveMediaQueries={attach:function(i,r){if(typeof Drupal.settings.highwireResponsive!='undefined'&&Drupal.settings.highwireResponsive.enquire_enabled===1&&Drupal.settings.highwireResponsive.breakpoints_configured===1){if(typeof Drupal.settings.highwireResponsive.breakpoints!='undefined'){o=!0}};if(o){var n=Drupal.settings.highwireResponsive.breakpoints;e.each(n,function(e,i){u[s]=e;s++;enquire.register(i,{match:function(){p(e)},unmatch:function(){a(e)}})});e(window,i).bind('load',function(){t()})}}}})(jQuery);